### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by theletterf**
Updated so that tech writers can't block PRs.

### CODE REVIEW

**Review by owais — APPROVED** [review]
I expected the first line to include all of the docs as well

**Comment by theletterf** [comment]
@owais You mean `*`? Not sure if I get your comment.

**Comment by owais** [comment]
Yes, wouldn't `*` match all files?

**Comment by theletterf** [comment]
Indeed. The idea here is that tech writers are included as reviewers for docs, but without exclusive approval power (we don't want tech writers to prevent PRs from going forward if a change in docs is not approved by one of them).

**Comment by owais** [comment]
OK. Either way, it stands approved :)

**Review by t2t2 — APPROVED** [review]

**Pull request merged**
