### PR TITLE
Update `SessionRecorder` type-definitions to match their use

### PR DESCRIPTION
**Pull request by jzaleski**
# Description

This change-set updates the type-definition and quick-start for `SplunkSessionRecorder` to match the preferred default-configuration.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Documentation update

# How has this been tested?

- Manual testing

### CODE REVIEW

**Comment by jzaleski** [comment]
@t2t2 can you please give this a review when you have a moment?

**Review by t2t2 — APPROVED** [review]

**Review by mhennoch — APPROVED** [review]

**Comment by jzaleski** [comment]
Thank you @t2t2 / @mhennoch -- when can we expect to see this in a release?

**Comment by t2t2** [comment]
Now released - https://github.com/signalfx/splunk-otel-js-web/releases/tag/v0.16.5

**Comment by jzaleski** [comment]
> Now released - https://github.com/signalfx/splunk-otel-js-web/releases/tag/v0.16.5

Excellent! It was a great experience working w/ you. Have a great day!

**Pull request merged**
